server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://produdoroDevUser:aVZrCoDJX3yLwVwO@wakanda.gymaztk.mongodb.net/wakanda?retryWrites=true&w=majority}
      auto-index-creation: true